# Generated by Django 5.1.6 on 2025-02-19 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('task', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
